export const RouteNames = {
  HOME: 'NAVBAR.HOME',
  ABOUT: 'NAVBAR.ABOUT',
  PORTFOLIO: 'NAVBAR.PORTFOLIO',
  EDUCATION: 'NAVBAR.EDUCATION',
  EXPERIENCE: 'NAVBAR.EXPERIENCE',
  PUBLICATIONS: 'NAVBAR.PUBLICATIONS'
}
